### ISSUE TITLE
Web Programming from Phone, Username?

### ISSUE THREAD

**Issue by JonnyBrando** [vbeskrovny/Cisco-Universal-AP#1]
I am not sure if this still works, but I just upgraded my WLC from a 2504 to a 9800..

To migrate my primed UX APs I had to factory reset them and wipe them. They are no longer primed.

We are checking if we can do CURL from windows...

We attempted to use the web page from a phone connected to a dedicated WLAN on the UX AP, but, it does nothing. Is this because the username & password is not being passed?

**Comment by damiantrx** [comment]
Hey, last week I did practically the same thing as you (also a 9800 controller)
Make sure:
- ap has ssh access enabled with login and password (by default this is not enabled on the 9800 - this is for acesspoint access by ssh/cli and make this curl possible)
- ssid network you are connecting to has the "universal admin" checkbox enabled
- ssid network with universal admin - is "paired" with vlan/subnet with access to IP of this UX-AP

Then you connect to the ssid with "universal admin" and do a post query to AP (I used Linux, I think the easiest way is to do it with WSL from microsoft store or by installing cygwin)

curl -v -X POST "http://MGMT_IP_OF_AP/set_universal_ap_reg_domain.shtml?configMode=1&location=**PL**&regDomain5=**-E**&regDomain24=**-E**" -u "admin:adminpassword"

U should get response "200"

**Comment by JonnyBrando** [comment]
Ahh, looked everywhere for the 'universal admin' checkbox!

Configuration -> Tags & Profiles -> WLANs -> Select your WLAN -> Advanced

Check off universal admin.

The web page is now available, and displays info from the AP.

It's a shame you can't program it from any PC. Have to be connected to a wlan assigned to the AP, with Universal Admin enabled, with an ID >= 17.

Already had SSH enabled, username, password, everything. Except that one checkbox. lol!

Thanks for the help!

**Comment by JonnyBrando** [comment]
Completed:

*   Trying 1.2.3.4:80...
* Connected to 1.2.3.4 (1.2.3.4) port 80 (#0)
* Server auth using Basic with user 'admin'
> POST /set_universal_ap_reg_domain.shtml?configMode=1&location=US&regDomain5=-B&regDomain24=-B HTTP/1.1
> Host: 1.2.3.4
> Authorization: Basic
> User-Agent: curl/7.82.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Wed, 13 Apr 2022 15:40:55 GMT
< Server: cisco-IOS
< Accept-Ranges: none
* no chunk, no close, no size. Assume close to signal end
<
* Closing connection 0

Rebooted, and comes up as US. Beautiful!
